### ISSUE TITLE
Setting limits on temperature

### ISSUE THREAD

**Issue by ares** [NETWAYS/check_smartvalues#3]
Nice plugin! Is there a way to override temperature limits in config file? I'm trying to do following

```
        "Seagate Barracuda 2.5 5400": {
            "Device" : ["Seagate Barracuda 2.5 5400"],
            "Threshs" : {
                "190": ["50", "60"]
            }
        }
```

190 is the temeprature sensor which shows 42 atm. However with this setting, the value is considered critical. When I change warning and critical to 30, 35 it's considered OK. I guess the comparison is > instead of <, is there a way to customize this? I haven't found it in readme.

Thanks!

**Comment by martialblog** [comment]
Hi, this repository will no longer be maintained and be archived soon.

We recommend these as replacement:

* https://github.com/thomas-krenn/check_smart_attributes
* https://github.com/Linuxfabrik/monitoring-plugins/tree/main/check-plugins/disk-smart
